### ISSUE TITLE
square gray background around animation

### ISSUE THREAD

**Issue by laith-abdo** [2d-inc/Flare-Swift#12]
how can i remove square dark gray color around the animation ?

**Comment by umberto-sonnino** [comment]
Do you mean in the example?
Just change the View background color [here](https://github.com/2d-inc/Flare-Swift/blob/0d5a23cb1b9183d9448dedc0841bdd843364d1ac/ExampleController/ViewController.swift#L27).

**Comment by laith-abdo** [comment]
![Screen Shot 2020-02-13 at 6 10 54 PM](https://user-images.githubusercontent.com/29063136/74454200-33d1d900-4e8c-11ea-9812-834c4cddad1e.png)

i mean dark gray square around animation , i changed the animation to another animation . 
dark gray square still around the animation 
how can i put only animation on clear view

**Comment by umberto-sonnino** [comment]
Currently, the background color is being set in [`ViewController.swift#L27`](https://github.com/2d-inc/Flare-Swift/blob/0d5a23cb1b9183d9448dedc0841bdd843364d1ac/ExampleController/ViewController.swift#L27), you can change it with the color you want - or remove it -  directly there.

**Comment by laith-abdo** [comment]
Dear , i mean this area ( that i selected with red square ) find the below image 


![Screen Shot 2020-02-13 at 6 31 11 PM](https://user-images.githubusercontent.com/29063136/74456308-4ac5fa80-4e8f-11ea-9d74-1767482d258e.png)

**Comment by umberto-sonnino** [comment]
For changing that background color you can provide your own values [here](https://github.com/2d-inc/Flare-Swift/blob/0d5a23cb1b9183d9448dedc0841bdd843364d1ac/FlareSkia/FlareSkView.swift#L125).
Just change the numerical ARGB numerical values for what you want. These values are `UInt32`s between 0 and 255 included.
To remove it: `sk_color_set_argb(0, 0, 0, 0)`
To set it to blue: `sk_color_set_argb(255, 0, 0, 255)`

**Comment by laith-abdo** [comment]
worked , thank you
