### ISSUE TITLE
Cannot Load File: Failed to open diagnostics file. json_reader.dia

### ISSUE THREAD

**Issue by brokenheist** [2d-inc/Flare-Swift#15]
Hi im having some issues trying to compile the FlareSwift, bellow an screenshot:

![image](https://user-images.githubusercontent.com/54251825/78852210-f6e01980-79d8-11ea-9eaa-99efc03d6991.png)

On the ./make_dependency.sh I received just one message about a HEAD referral:

![image](https://user-images.githubusercontent.com/54251825/78852253-10816100-79d9-11ea-9eea-c265a6aa7a97.png)

Any help would be appreciated.

OSX 10.15.4 (19E266)
Xcode Version 11.4 (11E146)

**Comment by phucledien** [comment]
Hey, have you solved this issue @brokenheist, can you help me with this? I'm facing this right now 😢
