### ISSUE TITLE
When support raster image support?

### ISSUE THREAD

**Issue by zhangjunmax** [2d-inc/Flare-Swift#4]
When support raster image support from Flare 1.1?

**Comment by zhangjunmax** [comment]
When support raster image support?

**Comment by umberto-sonnino** [comment]
We've got no ETA on it just yet, but we're hoping to having it out soon!

**Comment by zhangjunmax** [comment]
> We've got no ETA on it just yet, but we're hoping to having it out soon!

Thanks, is Flare-Flutter now support raste image?

**Comment by luigi-rosso** [comment]
Hi @zhangjunmax. Yes, Flare-Flutter does support raster images.

**Comment by zhangjunmax** [comment]
> Hi @zhangjunmax. Yes, Flare-Flutter does support raster images.

Thanks, I will try Flare-Flutter, another question, is Flare-Flutter support runtime raster images replacement(from remote server)?

**Comment by umberto-sonnino** [comment]
Hey @zhangjunmax we just merged a big update and this runtime now fully supports raster images!

Also, image replacement from the server is now available! [This is the API](https://github.com/2d-inc/Flare-Swift/blob/0d5a23cb1b9183d9448dedc0841bdd843364d1ac/FlareSkia/Drawables/flare_sk_image.swift#L114), and works in conjunction with dynamic image support in the Flare editor.
[Take a look at this Flare-Flutter example](https://gist.github.com/luigi-rosso/c50277341bd2681be072a575acbeb1fc), the logic and the workflow are the same!
