### ISSUE TITLE
sk_canvas.h' file not found

### ISSUE THREAD

**Issue by ashishpatelmi** [2d-inc/Flare-Swift#9]
Getting error

1)  Flare-Swift-master/FlareSwift/FlareSkia/Skia/Skia.h:1:10: 'src/include/c/sk_canvas.h' file not found
2) /FlareSwift/FlareSkia/Fills/flare_sk_color_fill.swift:10:8: Could not build Objective-C module 'Skia'

**Comment by umberto-sonnino** [comment]
Did you initialize the submodules for the repo? The file you're looking for should be there!
```
git clone git@github.com:2d-inc/Flare-Swift.git
cd Flare-Swift
git submodule update --init --recursive
./make_dependency.sh
```

**Comment by ashishpatelmi** [comment]
Yes I deed.. But still getting error

**Comment by umberto-sonnino** [comment]
Did you clone the repo via the `git clone` command?
If you just downloaded the repo's zip and unzipped it, submodule initialization won't work

**Comment by ashishpatelmi** [comment]
Hi @umberto-sonnino Thanks but getting new error 

> 
**./make_dependency.sh: line 44: ninja: command not found**

$ ./make_dependency.sh
Skipping "../src".
third_party/externals/Nima-Math-Cpp  @ e0c12772093fa8860f55358274515b86885f0108
third_party/externals/Nima-Cpp       @ 4bd02269d7d1d2e650950411325eafa15defb084
common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
third_party/externals/opencl-lib     @ 4e6d30e406d2e5a65e1d65e404fe6df5f772a32b
buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
third_party/externals/zlib           @ 47af7c547f8551bd25424e56354a2ae1e9062859
third_party/externals/spirv-headers  @ 661ad91124e6af2272afd00f804d8aa276e17107
third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
third_party/externals/egl-registry   @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
third_party/externals/libwebp        @ v1.0.2-rc1
third_party/externals/lua            @ v5-3-4
third_party/externals/spirv-tools    @ e9e4393b1c5aad7553c05782acefbe32b42644bd
third_party/externals/libjpeg-turbo  @ 2.0.0
third_party/externals/expat          @ android-6.0.1_r55
third_party/externals/freetype       @ 7edc937fe679d14d66f55cf6f7fa607925d38f3c
third_party/externals/libpng         @ v1.6.33
third_party/externals/wuffs          @ f58ffbc927899b9534a273d3057094ce6ac1ed61
third_party/externals/imgui          @ d38d7c6628bebd02692cfdd6fa76b4d992a35b75
warning: remote HEAD refers to nonexistent ref, unable to checkout.

third_party/externals/harfbuzz       @ 4f37ab63de9705d7bf74ee75364747e41b7c06a1
third_party/externals/sfntly         @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
third_party/externals/opencl-regi... @ 932ed55c85f887041291cef8019e54280c033c35
third_party/externals/sdl            @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
third_party/externals/angle2         @ 065f8dc35f9dffead39ced85a0ab1ba447ccf843
third_party/externals/opengl-regi... @ 14b80ebeab022b2c78f84a573f01028c96075553
third_party/externals/swiftshader    @ 64b761a8af9b7f15895de979e242d9d74f51321d
third_party/externals/icu            @ 407b39301e71006b68bd38e770f35d32398a7b14
Done. Made 47 targets from 26 files in 2216ms
./make_dependency.sh: line 44: ninja: command not found
mac-00019:Flare-Swift mac-00019$ ./make_dependency.sh
Skipping "../src".
buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
third_party/externals/Nima-Math-Cpp  @ e0c12772093fa8860f55358274515b86885f0108
third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
third_party/externals/lua            @ v5-3-4
common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
third_party/externals/Nima-Cpp       @ 4bd02269d7d1d2e650950411325eafa15defb084
third_party/externals/libjpeg-turbo  @ 2.0.0
third_party/externals/zlib           @ 47af7c547f8551bd25424e56354a2ae1e9062859
third_party/externals/opencl-lib     @ 4e6d30e406d2e5a65e1d65e404fe6df5f772a32b
third_party/externals/opengl-regi... @ 14b80ebeab022b2c78f84a573f01028c96075553
third_party/externals/sfntly         @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
third_party/externals/spirv-headers  @ 661ad91124e6af2272afd00f804d8aa276e17107
third_party/externals/libpng         @ v1.6.33
third_party/externals/icu            @ 407b39301e71006b68bd38e770f35d32398a7b14
third_party/externals/freetype       @ 7edc937fe679d14d66f55cf6f7fa607925d38f3c
third_party/externals/wuffs          @ f58ffbc927899b9534a273d3057094ce6ac1ed61
third_party/externals/libwebp        @ v1.0.2-rc1
third_party/externals/expat          @ android-6.0.1_r55
third_party/externals/spirv-tools    @ e9e4393b1c5aad7553c05782acefbe32b42644bd
third_party/externals/egl-registry   @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
third_party/externals/swiftshader    @ 64b761a8af9b7f15895de979e242d9d74f51321d
third_party/externals/angle2         @ 065f8dc35f9dffead39ced85a0ab1ba447ccf843
third_party/externals/imgui          @ d38d7c6628bebd02692cfdd6fa76b4d992a35b75
third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
third_party/externals/sdl            @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
third_party/externals/harfbuzz       @ 4f37ab63de9705d7bf74ee75364747e41b7c06a1
third_party/externals/opencl-regi... @ 932ed55c85f887041291cef8019e54280c033c35
Done. Made 47 targets from 26 files in 116ms
#./make_dependency.sh: line 44: ninja: command not found

**Comment by ashishpatelmi** [comment]
While building

I am running in Xcode 11

![Screenshot 2019-11-14 at 10 40 56 AM](https://user-images.githubusercontent.com/54980392/68828329-4f7de580-06cb-11ea-9936-597a40a08949.png)

**Comment by umberto-sonnino** [comment]
It seems that `ninja` is missing, that might be because you need to install `depot_tools`. You can follow the steps from [here](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up):

1. Clone the `depot_tools` repo in a folder in your file system:
```
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
```
2. Add depot_tools to the end of your PATH (you will probably want to put this in your ~/.bashrc or ~/.zshrc). Assuming you cloned depot_tools to /path/to/depot_tools:
```
export PATH=$PATH:/path/to/depot_tools
```

If `make_dependencies.sh` completes without error, XCode should be able to run the project  ..!

**Comment by ashishpatelmi** [comment]
Hi @umberto-sonnino Thank for your quick response.

This is error I am getting now

Xcode 11

![Screenshot 2019-11-15 at 1 18 11 PM](https://user-images.githubusercontent.com/54980392/68926014-75c68280-07aa-11ea-80dd-80014d07753d.png)

![Screenshot 2019-11-15 at 1 26 26 PM](https://user-images.githubusercontent.com/54980392/68926448-917e5880-07ab-11ea-9d8e-dbe8f9690b09.png)

**Comment by umberto-sonnino** [comment]
Sounds like Skia hasn't been built properly. Did you get any errors from running `make_dependencies.sh`? 
Are you trying to run on a Simulator or a physical device?

**Comment by ashishpatelmi** [comment]
@umberto-sonnino Thx it's working now.
